"""Command-line interface for opencap-to-nwb."""

from __future__ import annotations

import argparse
from pathlib import Path

from .convert import ConversionError, convert_session
from .discovery import discover_trials
from .nwb_inspection import InspectionError, inspect_nwb_file
from .nwb_validation import NwbValidationError
from .parsers import ParseError


def _add_common_input_argument(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Input session directory or OpenCap subject/session directory.",
    )


def build_convert_parser() -> argparse.ArgumentParser:
    """Build the conversion command-line argument parser."""
    parser = argparse.ArgumentParser(
        description="Convert OpenCap/OpenSim-style movement outputs to NWB."
    )

    _add_common_input_argument(parser)

    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Output NWB file path.",
    )

    parser.add_argument(
        "--trial",
        type=str,
        help="Trial name/stem to convert, for example Squats_0.",
    )

    parser.add_argument(
        "--metadata",
        type=Path,
        help="Explicit metadata YAML path. Defaults to <input>/metadata.yaml.",
    )

    parser.add_argument(
        "--trc",
        type=Path,
        help="Explicit TRC file path. Must be used with --mot.",
    )

    parser.add_argument(
        "--mot",
        type=Path,
        help="Explicit MOT file path. Must be used with --trc.",
    )

    parser.add_argument(
        "--no-validate-nwb",
        action="store_true",
        help="Skip NWB schema validation after writing.",
    )

    return parser


def build_list_trials_parser() -> argparse.ArgumentParser:
    """Build the list-trials command-line argument parser."""
    parser = argparse.ArgumentParser(
        description="List convertable OpenCap trials in an input directory."
    )
    _add_common_input_argument(parser)
    return parser


def build_inspect_parser() -> argparse.ArgumentParser:
    """Build the inspect command-line argument parser."""
    parser = argparse.ArgumentParser(
        description="Inspect an NWB file generated by opencap-to-nwb."
    )
    parser.add_argument(
        "path",
        type=Path,
        help="Path to the NWB file to inspect.",
    )
    return parser


def _list_trials(input_dir: Path) -> int:
    trials = discover_trials(input_dir)
    if not trials:
        print(f"No OpenCap trials found in: {input_dir}")
        return 1

    for trial in trials:
        print(trial.name)

    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the command-line interface."""
    if argv is None:
        import sys

        argv = sys.argv[1:]

    if argv and argv[0] == "list-trials":
        parser = build_list_trials_parser()
        args = parser.parse_args(argv[1:])
        return _list_trials(args.input)

    if argv and argv[0] == "inspect":
        parser = build_inspect_parser()
        args = parser.parse_args(argv[1:])

        try:
            inspect_nwb_file(args.path)
        except InspectionError as exc:
            parser.exit(status=1, message=f"error: {exc}\n")

        return 0

    parser = build_convert_parser()
    args = parser.parse_args(argv)

    try:
        output = convert_session(
            input_dir=args.input,
            output_path=args.output,
            trial=args.trial,
            metadata_path=args.metadata,
            trc_path=args.trc,
            mot_path=args.mot,
            validate_nwb=not args.no_validate_nwb,
        )
    except (ConversionError, ParseError, NwbValidationError) as exc:
        parser.exit(status=1, message=f"error: {exc}\n")

    print(f"Wrote NWB file: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
