"""Text inspection helpers for NWB files generated by opencap-to-nwb."""

from __future__ import annotations

from pathlib import Path
from typing import TextIO

import numpy as np
from pynwb import NWBHDF5IO


class InspectionError(RuntimeError):
    """Raised when an NWB file cannot be inspected."""


def _safe_shape(obj) -> str:
    data = getattr(obj, "data", None)
    shape = getattr(data, "shape", None)
    if shape is None:
        return "unknown"
    return str(tuple(shape))


def _safe_timestamp_summary(obj) -> tuple[str, str, str]:
    timestamps = getattr(obj, "timestamps", None)

    if timestamps is None:
        return "unknown", "unknown", "unknown"

    try:
        values = np.asarray(timestamps[:])
    except Exception:
        return "unknown", "unknown", "unknown"

    if values.size == 0:
        return "0", "unknown", "unknown"

    return str(values.size), str(float(values[0])), str(float(values[-1]))


def _print_timeseries_summary(name: str, obj, stream: TextIO) -> None:
    timestamp_count, first_timestamp, final_timestamp = _safe_timestamp_summary(obj)

    print(f"  {name}", file=stream)
    print(f"    shape: {_safe_shape(obj)}", file=stream)
    print(f"    unit: {getattr(obj, 'unit', 'unknown')}", file=stream)
    print(f"    timestamps: {timestamp_count}", file=stream)
    print(f"    first_timestamp: {first_timestamp}", file=stream)
    print(f"    final_timestamp: {final_timestamp}", file=stream)

    comments = getattr(obj, "comments", None)
    if comments:
        print(f"    comments: {comments}", file=stream)

    description = getattr(obj, "description", None)
    if description:
        print(f"    description: {description}", file=stream)


def inspect_nwb_file(path: str | Path, stream: TextIO | None = None) -> None:
    """Print a concise text summary of an NWB file."""
    import sys

    if stream is None:
        stream = sys.stdout

    path = Path(path)

    if not path.exists():
        raise InspectionError(f"NWB file does not exist: {path}")

    if not path.is_file():
        raise InspectionError(f"NWB path is not a file: {path}")

    try:
        with NWBHDF5IO(str(path), "r") as io:
            nwbfile = io.read()

            print(f"NWB file: {path}", file=stream)
            print(f"identifier: {nwbfile.identifier}", file=stream)
            print(f"session_id: {nwbfile.session_id}", file=stream)
            print(f"session_description: {nwbfile.session_description}", file=stream)

            subject = getattr(nwbfile, "subject", None)
            if subject is not None:
                print(f"subject_id: {getattr(subject, 'subject_id', None)}", file=stream)
            else:
                print("subject_id: None", file=stream)

            print("", file=stream)
            print("Processing modules:", file=stream)

            if not nwbfile.processing:
                print("  none", file=stream)
                return

            for module_name, module in nwbfile.processing.items():
                print(f"  {module_name}", file=stream)

                interface_names = list(module.data_interfaces.keys())
                if interface_names:
                    print(f"    interfaces: {', '.join(interface_names)}", file=stream)
                else:
                    print("    interfaces: none", file=stream)

            print("", file=stream)
            print("Behavior interfaces:", file=stream)

            behavior = nwbfile.processing.get("behavior")
            if behavior is None:
                print("  behavior module not found", file=stream)
                return

            for name, obj in behavior.data_interfaces.items():
                _print_timeseries_summary(name, obj, stream)

    except OSError as exc:
        raise InspectionError(f"Could not open NWB file {path}: {exc}") from exc
    